name: CI & Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  ci-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r booking/req.txt

    - name: Run Django tests
      run: python booking/manage.py test

    - name: Test Docker build
      run: docker compose build

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Archive files
      run: tar -czf deploy.tar.gz . || echo "tar warning, continue"

    - name: Copy to server
      run: scp deploy.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/deploy.tar.gz

    - name: SSH deploy
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e

          rm -rf ~/Hotel/booking
          mkdir -p ~/Hotel
          tar -xzf /tmp/deploy.tar.gz -C ~/Hotel --strip-components=1
          rm /tmp/deploy.tar.gz

          cd ~/Hotel/booking

          docker compose build
          docker compose up -d db nginx
          sleep 10

          docker compose run --rm web python manage.py migrate
          docker compose run --rm web python manage.py collectstatic --noinput

          docker compose up -d web
          docker compose ps

          echo "✅ Deployment completed"
        EOF
